/*player addAction["Take Canned food", "noscript.sqf", '_nobj = (nearestobjects [getpos player, ["Land_stand_small_EP1"],  5] select 0); _nobj setVariable["food",(_nobj getVariable "food")-1,true]; player setVariable["canfood",(player getVariable "canfood")+1,true]; player playmove "AinvPknlMstpSlayWrflDnon"; if(_nobj getVariable "food" < 1) then {_nobj spawn {_this setDamage 1; sleep 2; deleteVehicle _this;}; hint "You have taken some canned food\nNo more food left on the table";} else {hint format["You have taken some canned food\n(Table still has %1)", (_nobj getVariable "food")];};',0,false,false,"",'player distance (nearestobjects [getpos player, ["Land_stand_small_EP1"],  5] select 0) < 5 and (player getVariable "canfood") < 3 and (nearestobjects [getpos player, ["Land_stand_small_EP1"],  5] select 0) getVariable "food" > 0'];
*/
player addAction["Take Canned food", "noscript.sqf", 'deleteVehicle (nearestobjects [getpos player, ["Land_Bag_EP1"],  5] select 0); dzs_canfood = dzs_canfood + 1; hint "You have taken some canned food."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [getpos player, ["Land_Bag_EP1"],  5] select 0) < 5 and dzs_canfood<3 ']; 
player addAction["Bottle up water", "noscript.sqf", '(nearestobjects [getpos player, ["Land_Barrel_water"],  5] select 0) setVariable["water",((nearestobjects [getpos player, ["Land_Barrel_water"],  5] select 0) getVariable "water")-1,true]; dzs_water = dzs_water + 1; hint "You have taken some water."; player playmove "AinvPknlMstpSlayWrflDnon";',0,false,false,"",'player distance (nearestobjects [getpos player, ["Land_Barrel_water"],  5] select 0) < 5 and dzs_water < 4 and (nearestobjects [getpos player, ["Land_Barrel_water"],  5] select 0) getVariable "water" > 0'];
player addAction["Take bottle of water", "noscript.sqf", 'deleteVehicle (nearestobjects [getpos player, ["Land_Teapot_EP1"],  5] select 0); dzs_water = dzs_water + 1; hint "You have taken a bottle of water."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [getpos player, ["Land_Teapot_EP1"],  5] select 0) < 5 and dzs_water<4 '];
player addAction["Fill Water Bottle", "noscript.sqf", ' dzs_water = dzs_water + 1;; hint "You have filled a water bottle";',1,false,false,"",' player distance (nearestobjects [getpos player, ["Land_pumpa"],  3] select 0) < 3 and dzs_water<4'];
player addAction["Cook meat", "core\misc\cook.sqf", '', 1,false,false,"",'dzs_rabit > 0 OR dzs_cow > 0 OR dzs_chicken > 0 OR dzs_goat > 0 OR dzs_boar > 0 AND inflamed (nearestObjects[getPos player, ["Land_Campfire_burning"],5] select 0);'];

//Refuel at gas stations
//player addAction["Refuel Jerry can", "noscript.sqf", 'dzs_fuelF = true; dzs_fuelE = false; hint "You have refueled a empty jerry can";',0,false,false,"",'player distance (nearestObjects[getPos player, ["Land_A_FuelStation_Feed"], 3] select 0) < 3 AND !(dzs_fuelF) AND (dzs_fuelE)'];

//Gut animal actions?
player addAction["Take Raw Boar Meat", "noscript.sqf",'player switchMove "AinvPknlMstpSlayWrflDnon_medic"; AnimSync = [player,"AinvPknlMstpSlayWrflDnon_medic"]; publicVariable "AnimSync"; WaitUntil {animationState player != "AinvPknlMstpSlayWrflDnon_medic"}; dzs_boar = dzs_boar + 1; deleteVehicle (nearestObjects[getPos player, ["WildBoar"], 1] select 0); hint "You have taken some raw boar meat";',1,false,false,"",'not ALIVE (nearestObjects[getPos player, ["WildBoar"],  1] select 0) AND dzs_boar < 3 and dzs_boar_c < 3'];
player addAction["Take Raw Chicken Meat", "noscript.sqf",'player switchMove "AinvPknlMstpSlayWrflDnon_medic"; AnimSync = [player,"AinvPknlMstpSlayWrflDnon_medic"]; publicVariable "AnimSync"; WaitUntil {animationState player != "AinvPknlMstpSlayWrflDnon_medic"}; dzs_chicken = dzs_chicken + 1; deleteVehicle (nearestObjects[getPos player, ["cock","hen"], 1] select 0); hint "You have taken some raw chicken meat";',1,false,false,"",'not ALIVE (nearestObjects[getPos player, ["cock","hen"],  1] select 0) AND dzs_chicken < 3 and dzs_chicken_c < 4'];
player addAction["Take Raw Cow Meat", "noscript.sqf",'player switchMove "AinvPknlMstpSlayWrflDnon_medic"; AnimSync = [player,"AinvPknlMstpSlayWrflDnon_medic"]; publicVariable "AnimSync"; WaitUntil {animationState player != "AinvPknlMstpSlayWrflDnon_medic"}; dzs_cow = dzs_cow + 1; deleteVehicle (nearestObjects[getPos player, ["Cow01","Cow02","Cow03","Cow04"], 1] select 0); hint "You have taken some raw cow meat";',1,false,false,"",'NOT ALIVE (nearestObjects[getPos player, ["Cow01","Cow02","Cow03","Cow04"],  1] select 0) AND dzs_cow < 2 and dzs_cow_c < 2'];
player addAction["Take Raw Goat Meat", "noscript.sqf",'player switchMove "AinvPknlMstpSlayWrflDnon_medic"; AnimSync = [player,"AinvPknlMstpSlayWrflDnon_medic"]; publicVariable "AnimSync"; WaitUntil {animationState player != "AinvPknlMstpSlayWrflDnon_medic"}; dzs_goat = dzs_goat + 1; deleteVehicle (nearestObjects[getPos player, ["goat"], 1] select 0); hint "You have taken some raw goat meat";',1,false,false,"",'not ALIVE (nearestObjects[getPos player, ["goat"],  1] select 0) AND dzs_goat < 3 and dzs_goat_c < 3'];
player addAction["Take Raw Rabbit Meat", "noscript.sqf",'player switchMove "AinvPknlMstpSlayWrflDnon_medic"; AnimSync = [player,"AinvPknlMstpSlayWrflDnon_medic"]; publicVariable "AnimSync"; WaitUntil {animationState player != "AinvPknlMstpSlayWrflDnon_medic"}; dzs_rabit  = dzs_rabit + 1; deleteVehicle (nearestObjects[getPos player, ["Rabbit"], 1] select 0); hint "You have taken some raw rabbit meat";',1,false,false,"",'NOT ALIVE (nearestObjects[getPos player, ["Rabbit"],  1] select 0) AND dzs_rabit < 3 and dzs_rabit_c < 3'];

//Raw Meat Pickup Actions
player addAction["Take Raw Goat Meat", "noscript.sqf", 'deleteVehicle (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0); dzs_goat = dzs_goat + 1; hint "You have taken raw goat meat."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0) < 5 and dzs_goat < 3 and dzs_goat_c < 3 and ((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "item") == "goat" AND ((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "raw")'];
player addAction["Take Raw Cow Meat", "noscript.sqf", 'deleteVehicle (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0); dzs_cow = dzs_cow + 1; hint "You have taken raw cow meat."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0) < 5 and dzs_cow < 3 and dzs_cow_c < 2 and ((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "item") == "cow" AND ((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "raw")'];
player addAction["Take Raw Chicken Meat", "noscript.sqf", 'deleteVehicle (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0); dzs_chicken = dzs_chicken + 1; hint "You have taken raw chicken meat."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0) < 5 and dzs_chicken < 3 and dzs_chicken_c < 4 and ((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "item") == "chicken" AND ((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "raw")'];
player addAction["Take Raw Boar Meat", "noscript.sqf", 'deleteVehicle (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0); dzs_boar = dzs_boar + 1; hint "You have taken raw boar meat."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0) < 5 and dzs_boar < 3 and dzs_boar_c < 3 and ((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "item") == "boar" AND ((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "raw")'];
player addAction["Take Raw Rabbit Meat", "noscript.sqf", 'deleteVehicle (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0); dzs_rabit = dzs_rabit + 1; hint "You have taken raw rabbit meat."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0) < 5 and dzs_rabit < 3 and dzs_rabit_c < 4 and ((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "item") == "rabit" AND ((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "raw")'];

//Cooked Meat Pickup Actions
player addAction["Take Cooked Goat Meat", "noscript.sqf", 'deleteVehicle (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0); dzs_goat_c = dzs_goat_c + 1; hint "You have taken Cooked goat meat."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0) < 5 and dzs_goat < 3 and ((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "item") == "goat" AND !((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "raw") AND dzs_goat_c < 3'];
player addAction["Take Cooked Cow Meat", "noscript.sqf", 'deleteVehicle (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0); dzs_cow_c = dzs_cow_c + 1; hint "You have taken Cooked cow meat."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0) < 5 and dzs_cow < 3 and ((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "item") == "cow" AND !((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "raw") AND dzs_cow_c < 2'];
player addAction["Take Cooked Chicken Meat", "noscript.sqf", 'deleteVehicle (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0); dzs_chicken_c = dzs_chicken_c + 1; hint "You have taken Cooked chicken meat."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0) < 5 and dzs_chicken < 3 and ((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "item") == "chicken" AND !((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "raw") AND dzs_chicken_c < 4'];
player addAction["Take Cooked Boar Meat", "noscript.sqf", 'deleteVehicle (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0); dzs_boar_c = dzs_boar_c + 1; hint "You have taken Cooked boar meat."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0) < 5 and dzs_boar < 3 and ((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "item") == "boar" AND !((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "raw") AND dzs_boar_c < 3'];
player addAction["Take Cooked Rabbit Meat", "noscript.sqf", 'deleteVehicle (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0); dzs_rabit_c = dzs_rabit_c + 1; hint "You have taken Cooked rabbit meat."; player playmove "AinvPknlMstpSlayWrflDnon"',0,false,false,"",'player distance (nearestobjects [getpos player, ["Land_Sack_EP1"],  5] select 0) < 5 and dzs_rabit < 3 and ((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "item") == "rabit" AND !((nearestObjects[getPos player,["Land_Sack_EP1"], 5] select 0) getVariable "raw") AND dzs_rabit_c < 4'];

//Restrain them
//player addAction["Restrain player", "noscript.sqf",' [nil,(nearestObjects[player, ["Man","Man"], 3] select 1), rSwitchMove, "civillying01"] call RE;',0,false,false,"",' animationState (nearestObjects[player, ["Man","Man"], 3] select 1) == "adthpercmstpslowwrfldnon_4"'];
